// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyCXP7wP9tXyST-2ONbrmjpswJjz4_7EKUg',
  //   appId: '1:682372566037:web:a35f5554fb046d4313521c',
  //   messagingSenderId: '682372566037',
  //   projectId: 'demoproject-f305d',
  //   authDomain: 'demoproject-f305d.firebaseapp.com',
  //   databaseURL:
  //       'https://demoproject-f305d-default-rtdb.asia-southeast1.firebasedatabase.app',
  //   storageBucket: 'demoproject-f305d.appspot.com',
  //   measurementId: 'G-T93N77QKEL',
  // );
  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBdDZJc47QcavzIA4ZtWnreKwC7bRZ-m3I",
      authDomain: "sakumi-student.firebaseapp.com",
      projectId: "sakumi-student",
      storageBucket: "sakumi-student.appspot.com",
      messagingSenderId: "800259355994",
      appId: "1:800259355994:web:fee0c3e7ba537c26002f63",
      measurementId: "G-NB3XS046GH");
  // const firebaseConfig = {
  //   apiKey: "AIzaSyBdDZJc47QcavzIA4ZtWnreKwC7bRZ-m3I",
  //   authDomain: "sakumi-student.firebaseapp.com",
  //   projectId: "sakumi-student",
  //   storageBucket: "sakumi-student.appspot.com",
  //   messagingSenderId: "800259355994",
  //   appId: "1:800259355994:web:fee0c3e7ba537c26002f63",
  //   measurementId: "G-NB3XS046GH"
  // };

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsG1lIXRDrtcb-xyxRPX0omJNXWFce-D0',
    appId: '1:682372566037:android:89fc2ef64c4b5da813521c',
    messagingSenderId: '682372566037',
    projectId: 'demoproject-f305d',
    databaseURL:
        'https://demoproject-f305d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demoproject-f305d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDahHiPm_2eCDBw9skrwKsVkT78JRryZmY',
    appId: '1:682372566037:ios:84a26c22798d4e7613521c',
    messagingSenderId: '682372566037',
    projectId: 'demoproject-f305d',
    databaseURL:
        'https://demoproject-f305d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demoproject-f305d.appspot.com',
    androidClientId:
        '682372566037-dpd95ahlks5a7erraabnlo1kq3pimn0s.apps.googleusercontent.com',
    iosClientId:
        '682372566037-qf05ci2bdq4ca9qt900tjs47rkuumps3.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDahHiPm_2eCDBw9skrwKsVkT78JRryZmY',
    appId: '1:682372566037:ios:4cdb99a6303eec0913521c',
    messagingSenderId: '682372566037',
    projectId: 'demoproject-f305d',
    databaseURL:
        'https://demoproject-f305d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'demoproject-f305d.appspot.com',
    androidClientId:
        '682372566037-dpd95ahlks5a7erraabnlo1kq3pimn0s.apps.googleusercontent.com',
    iosClientId:
        '682372566037-3ps1d3mkja0k3pjas9962gr4bu6ek6rm.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseDemo.RunnerTests',
  );
}
