enum AppText {
  titleMultiChoice,
  btnReplay,
  textHello,
  titleInfo,
  btnLogout,
  btnLogin,
  textEmail,
  textPassword,
  textChangePass,
  textOldPass,
  textNewPass,
  textConfirmPass,
  textOldPassRequired,
  textNewPassRequired,
  textConfirmPassRequired,
  textPassNotMatch,
  textNotImgPick,
  textGeneral,
  textKaiwa,
  textJlpt,
  textClassIsEmpty,
  textLessons,
  textLessonsIsEmpty,
  textChooseCourse,
  txtChooseLesson,
  titleSkill,
  titleListening,
  titleKanji,
  titleVocabulary,
  titleGrammar,
  btnStart,
  textTest,
  titleHomework,
  btnSubmit,
  txtSubmitted,
  txtNotSubmit,
  btnCheckResult,
  textTrue,
  textFalse,
  textQuestion,
  textAnswer,
  textYourAnswer,
  textOpenCamera,
  textOpenGallery,
  textCancel,

  titleAdmin,
  titleMaster,
  titleManageStudent,
  titleManageClass,
  titleManageTag,
  titleManageBill,
  titleManageTeacher,
  titleManageFeedBack,
  titleRole,
  titleUserId,
  btnSignUp,
  selectorStudent,
  selectorTeacher,
  txtName,
  txtPhone,
  txtNote,
  txtAvatar,
  txtTeacherCode,
  txtStudentCode,
  txtClassId,
  txtCourseId,
  txtClassCode,
  txtLink,
  txtCourse,
  txtNumberOfLessons,
  txtRateOfAttendance,
  txtRateOfSubmitHomework,
  txtEvaluate,
  txtDescription,
  txtStartDate,
  txtEndDate,
  btnCreateClass,
  titleListClass,
  titleListStudent,
  titleListTeacher,
  btnAddNewClass,
  btnManageClass,
  btnManageStudent,
  btnAddNewStudent,
  btnAddTeacher,
  btnAddNewTeacher,
  btnUpdate,
  btnRemove,
  btnEdit,
  titleStatistics,
  btnAddStudent,
  titleAddTeacherToClass,
  txtNoStudent,
  txtNoClass,
  txtNoTag,
  txtNoTeacher,
  titleTagName,
  titleChooseBackground,
  titleChooseTextColor,
  btnAddTag,
  txtHello,
  txtSensei,
  subjectLesson,
  txtLesson,
  titleNoteBeforeTeaching,
  titleNoteFromSupport,
  titleNoteFromAnotherTeacher,
  txtNoteBeforeTeaching,
  txtNoteFromSupport,
  txtNoteFromAnotherTeacher,
  txtStartLesson,
  txtCompleteLesson,
  txtFinishLesson,
  txtQuantity,
  txtStudent,
  titleTimekeeping,
  txtPresent,
  txtNotPresent,
  txtAttendance,
  txtOutSoon,
  txtInLate,
  txtAbsent,
  txtPermitted,
  txtNotTimeKeeping,
  txtTest,
  txtPointOfTest,
  txtAveragePoint,
  txtDoHomeworks,
  txtNotMark,
  txtMarked,
  txtNoNoteForStudent,
  txtNoNoteForSupport,
  txtNoNoteForTeacher,
  txtHintNoteForStudentSendToSP,
  txtHintNoteForStudentSendToHV,
  txtHintNoteForSupport,
  txtHintNoteForTeacher,
  titleNoteForSenseiAfterTeach,
  txtNoteForSenseiAfterComplete,
  txtNoteForSenseiAfterTeach,
  txtQuestionForSenseiAfterTeach,
  txtBack,
  txtAgree,
  txtOK,
  txtActiveStatus,
  txtLearningStatus,
  titleOverView,
  titleLesson,
  titleGrading,
  textClass,
  textNumberResultReceive,
  textQuestionNumber,
  titleQuestion,
  textStudentNotDo,
  textBack,
  textStudentAnswer,
  textGradingScale,
  textShowName,
  textGeneralComment,
  titleSlogan,
  titleSakumiCenter,
  txtMessageLogin,
  txtHintAccount,
  txtHintPassword,
  txtForgetPassword,
  btnAdd,
  txtErrorStartDate,
  txtErrorEndDate,
  txtPleaseChooseCourse,
  txtPleaseInputClassCode,
  txtPleaseInputLink,
  txtPleaseCheckListClass,
  txtPleaseCheckListUser,
  txtPleaseCheckListStudentInClass,
  txtPleaseSelect,
  txtPleaseInputName,
  txtPleaseInputPhone,
  txtPleaseInputStudentCode,
  txtPleaseInputTeacherCode,
  txtPleaseInputEmail,
  txtStudentInJapan,
  statusInProgress,
  txtNotAttendance,
  txtGradingDone,
  textNumberNotGrading,
  titleSubject,
  titleStatus,
  textSSNote,
  titleHome,
  txtTeacherProfile,
  txtChangeImage,
  txtBaseInfo,
  txtPassLogin,
  txtCurrentPass,
  txtNewPass,
  txtAgainNewPass,
  txtChangePass,
  txtExit,
  txtUpdate,
  optInProgress,
  optComplete,
  optBoth,
  txtFilter,
  textStudentNotSubmit,
  textContactIT,
  textDetail,
  txtLogout,
  txtTeacherLogOut,
  txtRateOfSubmitTest,
  textLesson,
  stsCompleted,
  stsDropped,
  stsMoved,
  stsRetained,
  stsInProgress,
  stsViewer,
  txtTestEmpty,
  txtNotGradingTest,
  txtAssignmentTest,
  txtSSConfirmAssignTest,
  txtNotGrading,
  txtWrongPassword,
  txtWrongAccount,
  stsRenew,
  stsRemove,
  stsUpSale,
  txtType,
  textMarked,
  textNotMarked,
  txtInvalidLogin,
  txtConfirmDeleteClass,
  btnRemoveClass,
  txtEditClassInfo,
  txtClassType,
  txtChooseClassType,
  txtPleaseChooseType,
  txtConfirmChangeStatus,
  txtLoadMore,
  txtSearch,
  txtDoing,

  //master
  txtOption,
  txtManageCourse,
  txtAnother,
  txtSurvey,
  titleSurveyList,
  txtListCourse,
  txtListLesson,
  txtListTest,
  btnAddNewCourse,
  btnAddNewSurvey,
  btnAddNewLesson,
  btnAddNewTest,
  txtAddManual,
  txtAddFromJson,
  txtEditCourseInfo,
  btnDisableCourse,
  txtTermName,
  txtTermId,
  txtCode,
  txtLessonCount,
  txtLevel,
  txtTitle,
  txtToken,
  txtCourseType,
  txtPleaseInput,
  txtPleaseCheckListCourse,
  titleStdNumber,
  txtCol1,
  txtCol2,
  txtCol3,
  txtCol4,
  txtCol5,
  titleClassDes,
  titleClassNote,
  txtNoAttendance,
  txtNull,
  txtLastLesson,
  txtLastLessonEmpty,
  txtCourseState,
  txtDataVersion,
  txtLessonExist,
  txtCourseExist,
  txtTestExist,
  txtEditLessonInfo,
  txtLessonId,
  txtContent,
  txtPleaseCheckListLesson,
  txtRead,
  txtTeachingDay,
  txtDeleteLesson,
  txtGradingNumber,
  txtDoingTime,
  txtPoint,
  txtTeacherNote,
  txtNotGradingItem,
  txtNoteTeacherForSp,
  txtNoteSpForTeacher,
  txtNoteTeacherForAnotherSs,
  titleSearch,
  titleSearchGeneral,
  txtTeacher,
  txtClass,
  txtUpPercent,
  titleGeneralFeedBack,
  titleCurriculumFeedBack,
  titleLecturersFeedBack,
  titleStudentSupportFeedBack,
  titleRouteFeedBack,
  titleHomeworkFeedBack,
  titleTestFeedBack,
  titleTuitionFeedBack,
  titleFeedBackFromStd,
  txtUnread,
  txtWaiting,
  txtDone,
  titleListFeedBack,
  txtFeedBackEmpty,
  txtAddNote,
  txtLetNote,
  txtTool,
  txtNumberIgnore,
  txtAddNewTest,
  txtAddNewSurvey,
  txtEditTest,
  txtTestId,
  txtDifficult,
  txtPleaseCheckListTest,
  txtVoucher,
  txtPrefix,
  txtSuffix,
  txtUpdateStudentDone,
  txtReloadPass,
  txtSendReloadPassDone,
  txtUpdateTeacherDone,
  txtPleaseInputLinkAndTitle,
  txtSuccessfullyUpdateVideo,
  txtSuccessfullyUpdateVoucher,
  btnVerify,
  btnInputLinkAndTitle,
  txtNotLoggedIn,
  txtErrorInvalidFile,
  txtErrorInvalidFolder,
  txtErrorDuplicateLink,
  txtErrorDuplicateVideo,
  txtDuplicateLinkOrVideo,
  titleManageVoucher,
  titleVoucherCode,
  titleInfoVoucher,
  titleApplyCourse,
  titleExpiredDate,
  titleDiscount,
  txtAllCourse,
  txtJLPTCourse,
  txtKaiwaCourse,
  txtGeneralCourse,
  btnCreateVoucher,
  btnDownloadImage,
  txtVoucherNote1,
  txtVoucherNote2,
  txtVoucherNote3,
  titleSakumi,
  txtDirectDiscountVoucher,
  txtApplyFor,
  txtCreateNewVoucherSuccessfully,
  txtListStudentClass,
  txtNotStudentClass,
  txtNotTeacherClass,
  txtSeeSoon,
  txtAssignTest,
  txtNew,
  txtUsed,
  txtExpired,

  txtRecipientCode,
  txtEditAttendance,
  txtFullCourse,
  txtIgnore,
  txtSurveyCode,
  txtSurveyTitle,
  txtPleaseCheckListSurvey,
  txtDeleteSurvey,
  txtConfirmDeleteSurvey,
  btnAddNewSurveyQuestion,
  txtSurveyType1,
  txtSurveyType2,
  txtSurveyType3,
  txtSurveyType4,
  txtLetInputSurveyQuestion,
  txtLetInputSurveyAnswer,
  txtAnotherSetting,
  txtForce,
  txtActive,
  txtSave,
  btnAddNewSurveyAnswer,
  txtSaveSuccess,
  txtConfirmActiveSurvey,
  txtActiveSuccess,
  txtSurveyResultEmpty,
  txtDateAssignSurvey,
  txtRecall,
  txtSeeResult,
  txtConfirmAssignSurvey,
  txtConfirmRecallSurvey,
  txtSubmitNumber, txtSurveyEmpty,
  txtChooseQuestion,
  txtChooseAnswer,
  txtQuestion,
  txtAnswer,
  txtInformal,
  txtBillType,
  txtStdName,
  txtPaymentDate,
  txtPayment,
  txtRenewDate,
  txtNotBill,
  txtRefund,
  txtRevenue,
  txtChecked,
  txtEdit,
  titleBillDialog,
  txtDeleteBill,
  txtConfirmCheckBill,
  txtConfirmDeleteBill,
  txtCheck,
  txtMoney,
  txtErrorPaymentDate,
  txtErrorRenewDate,
  txtTabBill,
  txtBillEmpty,
  txtCreator,
  txtCurrency,
  txtCreatorFilter,
  titleAddBill,
  titleSendFeedback,
  txtSendFeedback,
  txtSendFeedBackToCentre,
  txtCentreFeedBack,
  txtTeachingFeedBack,
  txtSupportFeedBack,
  txtFeedBackType,
  txtFeedBack,
  txtPleaseInputFeedBack,
  txtAnonymous,
  txtAnonymousNote,
  titleFeedBackFromTeacher,
  titleStatisticsDashboard,
  txtBill,
  txtTotalBill,
  txtTotalBillThisMonth,
  txtNotCheck,
  txtTag,
  txtTotalClass,
  txtTotalClassThisMonth,
  txtTotalStudent,
  txtTotalStudentLearning,
  txtNotLog,
  txtStudentAddToClass,
  txtContentLog,
  txtSchedule,
  txtReport,
  txtNoReport,
  txtAdd,
  txtEditReport,
  txtAddNewReport,
  txtDeleteReport,
  txtTitleReport,
  txtPleaseInputReportTitle,
  txtContentReport,
  txtPleaseInputReportContent,
  txtCreatorReport,
  txtPleaseInputReportCreator,
  txtAddImage,
  txtAddReportImage,
  txtConfirmDeleteReport,
  txtFilterDate

}

Map<AppText, String> texts = {
  AppText.txtFilterDate : "Chọn ngày lọc: ",
  AppText.txtConfirmDeleteReport : "Xác nhận xoá biên bản...",
  AppText.txtAddReportImage : "Ảnh đính kèm",
  AppText.txtAddImage : "+THÊM ẢNH",
  AppText.txtPleaseInputReportCreator : "Vui lòng nhập tên người lập biên bản",
  AppText.txtCreatorReport : "Người lập biên bản",
  AppText.txtPleaseInputReportContent : "Vui lòng nhập tiêu đề biên bản",
  AppText.txtContentReport : "Nội dung biên bản",
  AppText.txtPleaseInputReportTitle : "Vui lòng nhập tiêu đề biên bản",
  AppText.txtTitleReport : "Tiêu đề biên bản",
  AppText.txtDeleteReport : "Xoá biên bản",
  AppText.txtAddNewReport : "Thêm biên bản mới",
  AppText.txtEditReport : "Chỉnh sửa biên bản",
  AppText.txtAdd : "+THÊM",
  AppText.txtNoReport : "Hiện sensei chưa có biên bản nào trong thời gian và trạng thái được chọn...",
  AppText.txtReport : "Biên bản",
  AppText.txtSchedule : "Lịch dạy",
  AppText.txtContentLog : "Học viên được chuyển từ @ sang #",
  AppText.txtStudentAddToClass : "Học viên được thêm mới vào lớp",
  AppText.txtNotLog : "Hiện tại không có ghi chép thay đổi của học viên phù hợp...",
  AppText.txtTotalStudentLearning : "Học viên Đang học",
  AppText.txtTotalStudent : "Tổng số học viên",
  AppText.txtTotalClassThisMonth : "Số lớp mở tháng này",
  AppText.txtTotalClass : "Tổng số lớp",
  AppText.txtTag : "Tag",
  AppText.txtNotCheck : "Chưa đối xoát",
  AppText.txtTotalBillThisMonth : "Hóa đơn tháng này",
  AppText.txtTotalBill : "Tổng số hóa đơn",
  AppText.txtBill : "Hoá đơn",
  AppText.titleStatisticsDashboard : "DASHBOARD THỐNG KÊ",
  AppText.txtAnonymousNote : "Chọn \"Ẩn Danh\" để góp ý không gửi kèm thông tin cá nhân",
  AppText.txtAnonymous : "Ẩn danh",
  AppText.txtPleaseInputFeedBack : "Vui lòng gửi góp ý cho trung tâm nếu có gì sensei thấy sai sót nhé...",
  AppText.txtFeedBack : "Góp ý",
  AppText.txtFeedBackType : "Loại Góp ý",
  AppText.txtSupportFeedBack : "Góp ý về Team Support",
  AppText.txtTeachingFeedBack : "Góp ý về Cách giảng dạy",
  AppText.txtCentreFeedBack : "Góp ý về Trung tâm",
  AppText.txtSendFeedBackToCentre : "Gửi góp ý đến trung tâm",
  AppText.txtSendFeedback : "Gửi Góp ý",
  AppText.titleSendFeedback : "GỬI GÓP Ý",
  AppText.titleAddBill : "+ THÊM HÓA ĐƠN",
  AppText.txtCreatorFilter : "Người tạo",
  AppText.txtCurrency : "Tiền tệ",
  AppText.txtCreator : "Người lập hoá đơn",
  AppText.txtBillEmpty : "Chưa có hoá đơn nào trong hệ thống!",
  AppText.txtTabBill : "Ghi nhận hóa đơn",
  AppText.txtErrorPaymentDate: 'Vui lòng chọn ngày đóng tiền trước ngày renew',
  AppText.txtErrorRenewDate: 'Vui lòng chọn ngày renew sau ngày đóng tiền',
  AppText.txtMoney : "Số tiền",
  AppText.txtConfirmDeleteBill : "Xác nhận xóa hóa đơn. Vui lòng kiểm tra kĩ trước khi xóa!",
  AppText.txtConfirmCheckBill : "Xác nhận đối xoát hóa đơn. Vui lòng kiểm tra kĩ trước khi đối xoát!",
  AppText.txtDeleteBill : "Xóa hóa đơn",
  AppText.titleBillDialog : "GHI NHẬN HÓA ĐƠN THANH TOÁN",
  AppText.txtEdit : "Chỉnh sửa",
  AppText.txtCheck : "Đối soát",
  AppText.txtChecked : "Đã đối xoát",
  AppText.txtRefund : "Tiền hoàn (refund): ",
  AppText.txtRevenue : "Ghi nhận doanh thu:",
  AppText.txtNotBill : "Hiện tại không có hoá đơn thoả mãn điều kiện, vui lòng chọn lại filter...",
  AppText.txtPaymentDate : "Ngày đóng tiền",
  AppText.txtPayment : "Số tiền đã đóng",
  AppText.txtRenewDate : "Ngày Renew",
  AppText.txtStdName : "Tên học viên",
  AppText.txtBillType : "Loại hoá đơn",
  AppText.txtInformal : "Lớp không chính thức",
  AppText.txtQuestion : "Câu hỏi",
  AppText.txtAnswer : "Câu trả lời",
  AppText.txtChooseQuestion : "Chọn câu hỏi",
  AppText.txtChooseAnswer : "Chọn câu trả lời",
  AppText.txtOption : "Điều kiện hiển thị",
  AppText.txtDoing : "Đang làm",
  AppText.txtSurveyEmpty: 'Không có bài khảo sát phù hợp để thêm vào lớp!',
  AppText.txtSubmitNumber: 'Có @ người trên # người trả lời câu hỏi này.',
  AppText.txtConfirmRecallSurvey: 'SS chắc chắn muốn thu hồi bài khảo sát này???',
  AppText.txtConfirmAssignSurvey: 'SS chắc chắn muốn giao bài khảo sát này???',
  AppText.txtSeeResult: 'Xem kết quả',
  AppText.txtRecall: 'Thu hồi',
  AppText.txtDateAssignSurvey: 'Ngày giao bài khảo sát ',
  AppText.txtSurveyResultEmpty: 'Hiện tại lớp chưa có bài khảo sát nào.',
  AppText.txtActiveSuccess: 'Kích hoạt thành công!',
  AppText.txtConfirmActiveSurvey: 'Xác nhận muốn kích hoạt bài khảo sát hay không? \nLưu ý: Kích hoạt thành công sẽ không thể chỉnh sửa bài khảo sát!',
  AppText.txtSaveSuccess: 'Lưu thành công!',
  AppText.btnAddNewSurveyAnswer: '+Thêm câu trả lời mới',
  AppText.txtActive: 'Kích hoạt',
  AppText.txtSave: 'Lưu',
  AppText.txtForce: 'Bắt buộc',
  AppText.txtAnotherSetting: 'Cài đặt khác',
  AppText.txtLetInputSurveyAnswer: 'Hãy điền câu trả lời khảo sát vào đây',
  AppText.txtLetInputSurveyQuestion: 'Hãy điền câu hỏi khảo sát vào đây',
  AppText.txtSurveyType1: 'Trắc nghiệm (cho chọn 1 lựa chọn)',
  AppText.txtSurveyType2: 'Hộp kiểm (cho chọn nhiều lựa chọn)',
  AppText.txtSurveyType3: 'Đoạn văn ngắn',
  AppText.txtSurveyType4: 'Đánh giá',
  AppText.btnAddNewSurveyQuestion: '+Thêm câu hỏi mới',
  AppText.txtConfirmDeleteSurvey: 'SS chắc chắn muốn xoá bài khảo sát này???',
  AppText.txtDeleteSurvey: 'Xoá bài',
  AppText.txtPleaseCheckListSurvey:
      'Bài khảo sát đã tồn tại, vui lòng kiểm tra mã bài khảo sát',
  AppText.txtSurveyTitle: 'Tiêu đề bài khảo sát',
  AppText.txtAddNewSurvey: 'Thêm bài khảo sát mới',
  AppText.btnAddNewSurvey: 'Thêm bài khảo sát',
  AppText.txtSurveyCode: 'Mã bài khảo sát',
  AppText.titleSurveyList: 'Danh sách bài khảo sát',
  AppText.txtSurvey: 'Khảo sát',
  AppText.txtIgnore: 'Bỏ qua',
  AppText.txtFullCourse: 'Full khoá',
  AppText.txtEditAttendance: 'Chỉnh sửa điểm danh',
  AppText.txtRecipientCode: 'Mã người nhận',
  AppText.txtNew: 'Mới',
  AppText.txtUsed: 'Đã sử dụng',
  AppText.txtExpired: 'Đã Hết hạn',
  AppText.txtCreateNewVoucherSuccessfully:
      'Mã voucher @ đã được tạo thành công',
  AppText.txtApplyFor: 'Áp dụng cho: @',
  AppText.txtDirectDiscountVoucher: 'Voucher Giảm Giá Trực Tiếp',
  AppText.titleSakumi: 'Nhật Ngữ Sakumi',
  AppText.txtVoucherNote1: '- Chỉ áp dụng tối đa 1 voucher cho 1 khoá học',
  AppText.txtVoucherNote2: '- Không áp dụng 2 chương trình khuyến mãi cùng lúc',
  AppText.txtVoucherNote3: '- Chỉ áp dụng khi đóng trọn khoá',
  AppText.btnCreateVoucher: 'Tạo voucher',
  AppText.btnDownloadImage: 'Tải ảnh',
  AppText.txtAllCourse: 'Tất Cả Khoá Học',
  AppText.txtJLPTCourse: 'Khoá Luyện Thi JLPT',
  AppText.txtKaiwaCourse: 'Khoá Học Giao Tiếp',
  AppText.txtGeneralCourse: 'Khoá Học Tổng Hợp',
  AppText.titleDiscount: 'Giá tiền giảm',
  AppText.titleInfoVoucher: 'Thông tin voucher',
  AppText.titleVoucherCode: 'Mã Voucher',
  AppText.titleApplyCourse: 'Khoá học áp dụng',
  AppText.titleExpiredDate: 'Ngày hết hạn',
  AppText.titleManageVoucher: 'Quản lý voucher',
  AppText.txtAssignTest: 'Giao bài',
  AppText.txtSeeSoon: 'Xem trước',
  AppText.txtNotTeacherClass: 'Giáo viên chưa tham gia dạy lớp nào!',
  AppText.txtNotStudentClass: 'Học viên chưa tham gia lớp nào!',
  AppText.txtListStudentClass: 'DANH SÁCH LỚP CỦA HỌC VIÊN',
  AppText.txtUpdateTeacherDone: 'Cập nhật Sensei thành công!',
  AppText.txtSendReloadPassDone:
      'Đã gửi mail cho học viên. Vui lòng thông báo cho học viên check mail để cập nhật mật khẩu mới!',
  AppText.txtReloadPass: 'Cập nhật mật khẩu',
  AppText.txtUpdateStudentDone: 'Cập nhật học sinh thành công!',
  AppText.txtNoteSpForTeacher: 'Ghi chú của team Support cho Sensei',
  AppText.txtPrefix: 'Tiền tố',
  AppText.txtSuffix: 'Hậu tố',
  AppText.txtVoucher: 'Voucher',
  AppText.txtDuplicateLinkOrVideo:
      'Trùng link meet hoặc trùng video, vui lòng kiểm tra lại',
  AppText.txtErrorInvalidFile:
      'Không tìm thấy file video trong drive MEET RECORDINGS SS',
  AppText.txtErrorInvalidFolder:
      'Không tìm thấy folder trong drive SCREEN RECORDING',
  AppText.txtErrorDuplicateLink: 'Trùng link meet trong sheet RENAME RECORD',
  AppText.txtErrorDuplicateVideo:
      'Trùng tên file video trong drive MEET RECORDINGS SS',
  AppText.txtNotLoggedIn: 'Bạn chưa xác thực tài khoản google',
  AppText.btnInputLinkAndTitle: 'Nhập Link và tiêu đề',
  AppText.btnVerify: 'Xác minh',
  AppText.txtSuccessfullyUpdateVideo: 'Đổi tên và di chuyển video thành công',
  AppText.txtSuccessfullyUpdateVoucher: 'Cập nhật voucher thành công',
  AppText.txtPleaseInputLinkAndTitle: 'Vui lòng nhập đường dẫn và tiêu đề',
  AppText.txtPleaseCheckListTest:
      'Bài kiểm tra đã tồn tại, vui lòng kiểm tra data...',
  AppText.txtDifficult: 'Độ khó',
  AppText.txtTestId: 'Mã bài kiểm tra',
  AppText.txtAddNewTest: 'Thêm bài kiểm tra mới',
  AppText.txtEditTest: 'Chỉnh sửa bài kiểm tra',
  AppText.txtNumberIgnore: 'Số câu bỏ qua',
  AppText.txtTool: 'Tool',
  AppText.txtLetNote: 'Hãy điền ghi chú vào đây',
  AppText.txtAddNote: 'Thêm ghi chú',
  AppText.txtFeedBackEmpty:
      'Đang không có góp ý, vui lòng chọn lại mục góp ý hoặc filter phù hợp...',
  AppText.titleListFeedBack: 'Danh sách góp ý',
  AppText.txtUnread: 'Chưa đọc',
  AppText.txtWaiting: 'Đang chờ được xử lí',
  AppText.txtDone: 'Đã xử lí',
  AppText.titleFeedBackFromTeacher: 'Góp ý từ sensei',
  AppText.titleFeedBackFromStd: 'Góp ý từ học viên',
  AppText.titleGeneralFeedBack: 'Góp ý Chung',
  AppText.titleCurriculumFeedBack: 'Góp ý về Giáo Trình',
  AppText.titleLecturersFeedBack: 'Góp ý về Giảng Viên',
  AppText.titleStudentSupportFeedBack: 'Góp ý về Hỗ Trợ Học Viên',
  AppText.titleRouteFeedBack: 'Góp ý về Lộ Trình',
  AppText.titleHomeworkFeedBack: 'Góp ý về Bài Tập Về Nhà',
  AppText.titleTestFeedBack: 'Góp ý về Kiểm Tra',
  AppText.titleTuitionFeedBack: 'Góp ý về Học Phí',
  AppText.txtUpPercent: 'Tỉ lệ lên kỳ',
  AppText.txtClass: 'Lớp học',
  AppText.txtTeacher: 'Giáo viên',
  AppText.titleSearchGeneral: 'Tìm kiếm chung',
  AppText.titleSearch: 'Tìm kiếm',
  AppText.txtNoteTeacherForAnotherSs:
      'Nhận xét của Sensei gửi cho Sensei tiếp theo',
  AppText.txtNoteTeacherForSp: 'Nhận xét của Sensei gửi cho Support',
  AppText.txtNotGradingItem:
      'Bạn chưa có bài nào để chấm, có thể chọn lại filter để show các bài ... ',
  AppText.txtTeacherNote: 'Nhận xét của Giáo viên',
  AppText.txtDoingTime: 'Thời gian làm bài',
  AppText.txtPoint: 'Điểm số',
  AppText.txtGradingNumber: 'Số bài đã chấm',
  AppText.titleManageFeedBack: 'Góp ý',
  AppText.txtDeleteLesson: 'Xoá bài học',
  AppText.txtTeachingDay: 'Ngày dạy',
  AppText.txtRead: 'Tôi đã đọc ghi chú',
  AppText.btnAddNewStudent: 'Thêm học viên mới',
  AppText.txtPleaseCheckListLesson:
      'Bài học đã tồn tại, vui lòng kiểm tra lại!',
  AppText.txtContent: 'Nội dung',
  AppText.txtLessonId: 'Mã bài học',
  AppText.txtEditLessonInfo: 'Chỉnh sửa thông tin bài học',
  AppText.txtLessonExist: 'File có lesson Id đã tồn tại',
  AppText.txtCourseExist: 'File có course Id đã tồn tại',
  AppText.txtTestExist: 'File có test Id đã tồn tại',
  AppText.txtDataVersion: 'Data Version',
  AppText.txtCourseState: 'Tình trạng khoá học',
  AppText.txtLastLessonEmpty: 'Lớp chưa mở bài học nào!',
  AppText.txtLastLesson: 'Bài học gần đây:',
  AppText.txtNull: 'Null',
  AppText.txtNoAttendance: 'Không điểm danh',
  AppText.titleClassDes: 'Mô tả của lớp',
  AppText.titleClassNote: 'Ghi chú của lớp',
  AppText.txtCol1: 'Hoàn thành/Đang học',
  AppText.txtCol2: 'Người xem',
  AppText.txtCol3: 'Chuyển lớp',
  AppText.txtCol4: 'Lên kỳ/Bắt buộc lên kỳ',
  AppText.txtCol5: 'Bảo lưu/Nghỉ/Bỏ cọc',
  AppText.titleStdNumber: 'Số lượng học viên',
  AppText.btnDisableCourse: 'xoá khoá học',
  AppText.txtEditCourseInfo: 'Chỉnh sửa khoá học',
  AppText.txtPleaseCheckListCourse:
      'Khoá học đã tồn tại, vui lòng kiểm tra lại',
  AppText.txtPleaseInput: 'Vui lòng không để trống',
  AppText.txtTermName: 'Tên học kì',
  AppText.txtTermId: 'Mã học kì',
  AppText.txtCode: 'Code',
  AppText.txtLessonCount: 'Số bài học',
  AppText.txtLevel: 'Trình độ',
  AppText.txtToken: 'Token',
  AppText.txtTitle: 'Tiêu đề',
  AppText.txtCourseType: 'Type',
  AppText.txtAddManual: 'Thêm thủ công',
  AppText.txtAddFromJson: 'Thêm từ FILE',
  AppText.btnAddNewCourse: 'Thêm khoá học mới',
  AppText.btnAddNewLesson: 'Thêm bài học mới',
  AppText.btnAddNewTest: 'Thêm bài kiểm tra mới',
  AppText.txtListLesson: 'Danh sách bài học',
  AppText.txtListTest: 'Danh sách bài test',
  AppText.txtListCourse: 'Danh sách khoá học',
  AppText.txtAnother: 'Ý kiến khác',
  AppText.txtManageCourse: 'Quản lý khoá học',
  AppText.txtSearch: 'Tìm kiếm...',
  AppText.txtLoadMore: 'Xem thêm',
  AppText.txtConfirmChangeStatus:
      'SS chắc chắn muốn thay đổi\n trạng thái của @ từ % sang #',
  AppText.txtPleaseChooseType: 'Vui lòng chọn loại lớp',
  AppText.txtEditClassInfo: 'Chỉnh sửa thông tin lớp học',
  AppText.txtConfirmDeleteClass: 'SS chắc chắn muốn xoá lớp @ hay không?',
  AppText.txtInvalidLogin: 'Thông tin đăng nhập không hợp lệ',
  AppText.textNotMarked: 'Chưa chấm',
  AppText.textMarked: 'Đã chấm',
  AppText.txtChooseClassType: 'Chọn loại lớp',
  AppText.txtClassType: 'Loại lớp',
  AppText.txtType: 'Loại bài',
  AppText.stsUpSale: 'Lên cấp',
  AppText.btnRemoveClass: 'Xoá lớp',
  AppText.stsRemove: 'Đã xoá',
  AppText.stsRenew: 'ReNew',
  AppText.txtNotGrading: 'Chưa chấm',
  AppText.txtSSConfirmAssignTest: 'Sensei có đồng ý giao bài hay không?',
  AppText.txtAssignmentTest: 'Giao bài kiểm tra',
  AppText.txtNotGradingTest: 'Chưa chấm bài kiểm tra',
  AppText.txtTestEmpty: 'Chưa có bài kiểm tra có thể giao trong lớp!',
  AppText.textLesson: 'Bài',
  AppText.txtRateOfSubmitTest: 'Tỉ lệ nộp bài',
  AppText.textDetail: 'Chi tiết',
  AppText.textStudentNotSubmit: 'Lớp chưa có ai nộp bài tập!',
  AppText.textContactIT:
      'Lỗi khi load data, vui lòng liên hệ team IT để được support',
  AppText.titleHome: 'Trang chủ',
  AppText.textSSNote: 'Sensei hãy nhận xét về bài làm của Học viên nhé...',
  AppText.txtGradingDone: 'Chấm điểm xong!',
  AppText.textNumberNotGrading: 'Số bài chưa chấm: ',
  AppText.textShowName: 'Hiện tên',
  AppText.textGeneralComment: 'Nhận xét chung',
  AppText.textGradingScale: 'Thang điểm',
  AppText.textStudentAnswer: 'Đáp án của Học viên: ',
  AppText.textBack: 'Quay về',
  AppText.textStudentNotDo: 'Học viên đã bỏ qua câu này!',
  AppText.titleQuestion: 'CÂU HỎI',
  AppText.textQuestionNumber: 'CÂU SỐ ',
  AppText.textNumberResultReceive: 'Số bài nhận được',
  AppText.textClass: 'Lớp',
  AppText.titleOverView: 'Tổng quan',
  AppText.titleLesson: 'Bài học',
  AppText.titleGrading: 'Chấm điểm',
  AppText.titleMultiChoice: 'Kiểm tra',
  AppText.btnReplay: 'Làm lại',
  AppText.btnSubmit: 'Nộp bài',
  AppText.txtSubmitted: 'Đã nộp',
  AppText.txtNotSubmit: 'Chưa nộp',
  AppText.btnCheckResult: 'Chi tiết bài làm',
  AppText.textHello: 'Chào mừng tới SAKUMI',
  AppText.titleInfo: 'Thông tin cá nhân',
  AppText.btnLogin: 'Đăng nhập',
  AppText.btnLogout: 'Đăng xuất',
  AppText.textEmail: 'Email',
  AppText.textPassword: 'Mật khẩu',
  AppText.textChangePass: 'Đổi mật khẩu',
  AppText.textOldPass: 'Mật khẩu cũ',
  AppText.textNewPass: 'Mật khẩu mới',
  AppText.textConfirmPass: 'Xác nhận mật khẩu',
  AppText.textOldPassRequired: 'Mật khẩu cũ không được trống',
  AppText.textNewPassRequired: 'Mật khẩu mới không được trống',
  AppText.textConfirmPassRequired: 'Chưa xác nhận mật khẩu',
  AppText.textPassNotMatch: 'Mật khẩu xác nhận chưa khớp',
  AppText.textNotImgPick: 'Không có ảnh được chọn',
  AppText.textGeneral: 'Khoá học tổng hợp',
  AppText.textKaiwa: 'Khoá học Kaiwa',
  AppText.textJlpt: 'Khoá học JLPT',
  AppText.textClassIsEmpty: 'Bạn chưa đăng ký bất kì lớp học nào',
  AppText.textLessons: 'Danh sách bài học',
  AppText.textLessonsIsEmpty: 'Đang cập nhật bài học, vui lòng thử lại sau!',
  AppText.textChooseCourse: 'Chọn khóa học',
  AppText.txtChooseLesson: 'Chọn bài học',
  AppText.titleSkill: 'Luyện kỹ năng',
  AppText.titleListening: 'luyện nghe',
  AppText.titleKanji: 'kanji',
  AppText.titleVocabulary: 'từ vựng',
  AppText.titleGrammar: 'ngữ pháp',
  AppText.btnStart: 'Bắt đầu ngay',
  AppText.textTest: 'Đừng để những ngày tháng học tập của bạn trở nên vô nghĩa',
  AppText.titleHomework: 'Bài tập về nhà',
  AppText.textTrue: 'Đúng',
  AppText.textFalse: 'Sai',
  AppText.textQuestion: 'Câu hỏi:  ',
  AppText.textAnswer: 'Đáp án đúng:  ',
  AppText.textYourAnswer: 'Đáp án của bạn:  ',
  AppText.textOpenCamera: 'Chụp ảnh mới',
  AppText.textOpenGallery: 'Chọn ảnh từ thư viện',
  AppText.textCancel: 'Thoát',
  AppText.titleAdmin: 'Admin',
  AppText.titleMaster: 'Master',
  AppText.titleManageStudent: 'Danh sách học viên',
  AppText.titleManageClass: 'Danh sách lớp học',
  AppText.titleManageTag: 'Quản lý tag',
  AppText.titleManageTeacher: 'Quản lý giáo viên',
  AppText.titleManageBill: 'Quản lý hoá đơn',
  AppText.titleRole: 'Vai trò',
  AppText.titleUserId: 'Mã người dùng',
  AppText.btnSignUp: 'Đăng ký',
  AppText.selectorStudent: 'student',
  AppText.selectorTeacher: 'teacher',
  AppText.txtName: 'Họ tên',
  AppText.txtPhone: 'Số điện thoại',
  AppText.txtNote: 'Ghi chú',
  AppText.txtTeacherCode: 'Mã giáo viên',
  AppText.txtStudentCode: 'Mã học viên',
  AppText.txtClassId: 'Mã định danh lớp',
  AppText.txtCourseId: 'Mã khoá học',
  AppText.txtClassCode: 'Mã lớp',
  AppText.txtLink: 'Link google meet',
  AppText.txtCourse: 'Khoá học',
  AppText.txtNumberOfLessons: 'Số buổi học',
  AppText.txtRateOfAttendance: 'Tỉ lệ đi học',
  AppText.txtRateOfSubmitHomework: 'Tỉ lệ làm bài tập',
  AppText.txtEvaluate: 'Đánh giá',
  AppText.txtDescription: 'Mô tả',
  AppText.txtStartDate: 'Ngày bắt đầu',
  AppText.txtEndDate: 'Ngày kết thúc',
  AppText.btnCreateClass: 'Tạo lớp mới',
  AppText.titleListClass: 'Danh sách các lớp',
  AppText.titleListStudent: 'Danh sách học viên',
  AppText.titleListTeacher: 'Danh sách giáo viên',
  AppText.btnAddNewClass: 'Thêm lớp học mới',
  AppText.btnManageClass: 'Quản lý lớp học',
  AppText.btnManageStudent: 'Quản lý học viên',
  AppText.btnAddTeacher: 'Thêm giáo viên',
  AppText.btnAddNewTeacher: 'Thêm giáo viên mới',
  AppText.btnUpdate: 'Cập nhật',
  AppText.btnRemove: 'Xoá',
  AppText.btnEdit: 'Sửa',
  AppText.titleStatistics: 'Thống kê',
  AppText.btnAddStudent: 'Thêm học viên',
  AppText.titleAddTeacherToClass: 'Thêm giáo viên vào lớp',
  AppText.txtNoStudent: 'Không có học viên',
  AppText.txtNoTeacher: 'Không có giáo viên',
  AppText.txtNoClass: 'Không có lớp học thoả mãn điều kiện, vui lòng chọn lại filter...',
  AppText.txtNoTag: 'Không có thẻ',
  AppText.titleTagName: 'Tên thẻ',
  AppText.titleChooseBackground: 'Chọn màu nền',
  AppText.titleChooseTextColor: 'Chọn màu chữ',
  AppText.txtHello: 'Xin chào',
  AppText.txtSensei: 'Sensei',
  AppText.txtLesson: 'Buổi',
  AppText.subjectLesson: 'Buổi học',
  AppText.titleNoteBeforeTeaching: 'Dặn dò trước buổi học',
  AppText.titleNoteFromSupport: 'Ghi chú từ Team Support',
  AppText.titleNoteFromAnotherTeacher: 'Ghi chú từ Sensei',
  AppText.txtNoteBeforeTeaching:
      'Sensei vui lòng bật record Google Meet trước khi bắt đầu buổi học',
  AppText.txtNoteFromSupport:
      'Sensei vui lòng liên hệ số điện thoại 0xxxxxxxxx khi cần hỗ trợ về trang thiết bị',
  AppText.txtNoteFromAnotherTeacher:
      'Sensei vui lòng liên hệ số điện thoại 0xxxxxxxxx khi cần hỗ trợ về giảng dạy',
  AppText.txtStartLesson: 'Bắt đầu buổi học',
  AppText.txtCompleteLesson: 'Hoàn thành buổi học',
  AppText.txtFinishLesson: 'Kết thúc buổi học',
  AppText.txtQuantity: 'Sỉ số',
  AppText.txtStudent: 'Học viên',
  AppText.titleTimekeeping: 'Điểm danh',
  AppText.txtPresent: 'Có mặt',
  AppText.txtNotPresent: 'Vắng mặt',
  AppText.txtAttendance: 'Đi học',
  AppText.txtOutSoon: 'Ra sớm',
  AppText.txtInLate: 'Vào trễ',
  AppText.txtAbsent: 'Nghỉ KP',
  AppText.txtPermitted: 'Nghỉ CP',
  AppText.txtNotTimeKeeping: 'Chưa điểm danh',
  AppText.txtTest: 'Bài kiểm tra',
  AppText.txtPointOfTest: 'Điểm kiểm tra',
  AppText.txtAveragePoint: 'Điểm trung bình',
  AppText.txtDoHomeworks: 'Làm BTVN',
  AppText.txtNotMark: 'Chưa chấm bài',
  AppText.txtMarked: 'Đã chấm bài ',
  AppText.txtNoNoteForStudent: 'Không có dặn dò dành cho học viên',
  AppText.txtNoNoteForSupport: 'Không có dặn dò dành cho Team Support',
  AppText.txtNoNoteForTeacher: 'Không có dặn dò dành cho Sensei',
  AppText.txtHintNoteForStudentSendToSP:
      'Điền ghi chú của Sensei dành cho học viên...(Gửi cho Support)',
  AppText.txtHintNoteForStudentSendToHV:
      'Điền ghi chú của Sensei dành cho học viên...(Gửi cho tất cả Học viên)',
  AppText.txtHintNoteForSupport: 'Điền ghi chú dành cho Team Support...',
  AppText.txtHintNoteForTeacher: 'Điền ghi chú dành cho Sensei tiếp theo...',
  AppText.titleNoteForSenseiAfterTeach: 'Dặn dò dành cho Sensei cuối buổi học',
  AppText.txtNoteForSenseiAfterTeach:
      'Sensei vui lòng tắt record Google Meet trước khi bấm đồng ý kết thúc buổi học',
  AppText.txtNoteForSenseiAfterComplete:
      "Sensei vui lòng kiểm tra các ghi chú trước khi bấm đồng ý hoàn thành buổi học",
  AppText.txtQuestionForSenseiAfterTeach:
      'Sensei có muốn kết thúc buổi học không?',
  AppText.txtAgree: 'Đồng ý',
  AppText.txtOK: 'OK',
  AppText.txtBack: 'Quay lại',
  AppText.txtActiveStatus: 'Tương tác',
  AppText.txtLearningStatus: 'Học lực',
  AppText.titleSakumiCenter: 'Trung tâm Nhật ngữ Sakumi',
  AppText.titleSlogan: 'Tri thức truyền từ tâm',
  AppText.txtMessageLogin:
      'Các sensei hãy đăng nhập để có thể sử dụng đầy đủ các chức năng hỗ trợ trong việc đứng lớp nhé!',
  AppText.txtHintAccount: 'abc123@gmail.com',
  AppText.txtHintPassword: 'abc123',
  AppText.txtForgetPassword: 'Quên mật khẩu',
  AppText.btnAdd: 'Thêm mới',
  AppText.txtErrorEndDate: 'Vui lòng chọn ngày kết thúc sau ngày bắt đầu',
  AppText.txtErrorStartDate: 'Vui lòng chọn ngày bắt đầu trước ngày kết thúc',
  AppText.txtPleaseChooseCourse: 'Vui lòng chọn khoá học',
  AppText.txtPleaseInputClassCode: 'Vui lòng nhập mã lớp học',
  AppText.txtPleaseInputLink: 'Vui lòng nhập link lớp học',
  AppText.txtPleaseCheckListClass:
      'Mã lớp đã tồn tại. Vui lòng kiểm tra lại danh sách lớp',
  AppText.txtPleaseCheckListUser:
      'Tài khoản này đã tồn tại. Vui lòng kiểm tra lại danh sách người dùng',
  AppText.txtPleaseCheckListStudentInClass:
      'Học viên này đã được thêm vào lớp. Vui lòng kiểm tra lại danh sách học viên trong lớp',
  AppText.txtPleaseSelect: 'Vui lòng lựa chọn',
  AppText.txtPleaseInputName: 'Vui lòng nhập tên',
  AppText.txtPleaseInputStudentCode: 'Vui lòng nhập mã học viên',
  AppText.txtPleaseInputTeacherCode: 'Vui lòng nhập mã giáo viên',
  AppText.txtPleaseInputEmail: 'Vui lòng nhập email',
  AppText.txtStudentInJapan: 'Học viên ở Nhật Bản',
  AppText.statusInProgress: 'InProgress',
  AppText.txtNotAttendance: 'Ko điểm danh',
  AppText.titleSubject: 'Tựa đề bài',
  AppText.titleStatus: 'Trạng thái',
  AppText.optBoth: 'Cả 2',
  AppText.optInProgress: 'Đang diễn ra',
  AppText.optComplete: 'Đã kết thúc',
  AppText.txtFilter: 'Bộ lọc',
  AppText.txtTeacherProfile: 'Profile Giáo viên',
  AppText.txtChangeImage: 'Đổi ảnh mới',
  AppText.txtBaseInfo: 'Thông tin cơ bản',
  AppText.txtPassLogin: 'Thay đổi mật khẩu',
  AppText.txtCurrentPass: 'Mật khẩu hiện tại',
  AppText.txtNewPass: 'Mật khẩu mới',
  AppText.txtAgainNewPass: 'Nhập lại mật khẩu mới',
  AppText.txtChangePass: 'Đổi mật khẩu',
  AppText.txtUpdate: 'Cập nhật',
  AppText.txtExit: 'Thoát',
  AppText.txtLogout: 'Đăng xuất',
  AppText.txtTeacherLogOut: 'Sensei có đồng ý đăng xuất hay không?',
  AppText.stsCompleted: 'Đã hoàn thành',
  AppText.stsDropped: 'Huỷ lớp',
  AppText.stsMoved: 'Chuyển lớp',
  AppText.stsRetained: 'Giữ lại',
  AppText.stsInProgress: 'Đang học',
  AppText.stsViewer: 'Người xem',
  AppText.txtWrongPassword: 'Vui lòng kiểm tra lại mật khẩu',
  AppText.txtWrongAccount: 'Vui lòng kiểm tra lại tài khoản',
};

extension AppTexts on AppText {
  static String getStringValue(String value) {
    return value;
  }

  String get text => texts[this] ?? '--TextNotFound--';
}

String vietnameseSubTextTeacher(String text) {
  switch (text) {
    case 'Remove':
      return "Xoá";
    case 'InProgress':
      return "Đang Dạy";
    default:
      return "error";
  }
}

String vietnameseSubText(String text) {
  switch (text) {
    case 'Completed':
      return "Hoàn Thành";
    case 'Moved':
      return "Chuyển Lớp";
    case 'UpSale':
      return "Lên Kỳ";
    case 'Retained':
      return "Bảo Lưu";
    case 'ReNew':
      return "Đăng Ký Lại";
    case 'Dropped':
      return "Nghỉ Học";
    case 'Remove':
      return "Xoá";
    case 'Viewer':
      return "Người Xem";
    case 'InProgress':
      return "Đang Học";
    case 'Cancel':
      return "Huỷ";
    case 'Preparing':
      return "Mới Tạo";
    case "Deposit":
      return "Bỏ cọc";
    case "Force":
      return "Bắt buộc lên kỳ";
    default:
      return "error";
  }
}

String priceVND(String text) {
  if ( text.length > 3) {
    int count = 0;
    List<String> price = [];
    do {
      int end = text.length - 3 * count;
      int start = end - 3 < 0 ? 0 : end - 3;
      String temp = text.substring(start, end);

      if (temp != '') {
        price.add(temp);
      }
      count++;
    } while (count <= text.length ~/ 3);

    return price.reversed.join('.');
  } else {
    return text;
  }
}
